### ISSUE TITLE
weird checkbox behaviour

### ISSUE THREAD

**Issue by dereke** [featurist/browser-monkey#15]
getting a checkbox to go into a checked state can be difficult.
it seems to work OK if you click on a checkboxes label but not if you click on the checkbox itself

please write some more tests for this use case

**Comment by refractalize** [comment]
I did some work on this in #7, can't remember where I left it tho

**Comment by dereke** [comment]
OK, cool I will have a look sometime, just created the issue as @adiel was seeing this weird behaviour and I needed a reminder to look at it when I have time :-)

**Comment by dereke** [comment]
I am going to close this as there seem to be tests around all the cases you would expect and this has been open for a year without any further issues.
