### ISSUE TITLE
Better error messages when "click" does not find element

### ISSUE THREAD

**Issue by artemave** [featurist/browser-monkey#26]
Here is what I am getting now:

![screen shot 2016-02-18 at 18 05 17](https://cloud.githubusercontent.com/assets/23721/13153093/3c701aca-d66a-11e5-948d-c5b8dbb1e958.png)

**Comment by dereke** [comment]
hmmm this isn't quite what I am seeing. I get `expected to find: .css-path-of-element`.
But I am not using cucumber, I wonder if that is the difference?

**Comment by artemave** [comment]
Could well be...

**Comment by dereke** [comment]
this is much better now - the stack starts at the assertion that failed.
It could probably be better with some stack trace "cleaning" feel free to follow up on that :-)
