### ISSUE TITLE
timeout option for "click"

### ISSUE THREAD

**Issue by artemave** [featurist/browser-monkey#27]
Otherwise it seems like I need to `shouldHave` before I can safely `click`.

**Comment by adiel** [comment]
Really? I'm sure that's not the intention..

**Comment by dereke** [comment]
@artemave click will wait for the element to appear before clicking on it. It will never try and do anything until there is an element - same goes for any of the other actions.
The docs probably don't make this clear but you can adjust the timeouts and try interval:

 - options.timeout - length of time to wait for the element (1000ms)
 - options.interval - time between testing the dom (10ms)

does that help?

**Comment by artemave** [comment]
Ah, I was passing `timeout` to `find`, rather than `click`. That is not supported, which was a bit counterintuitive, but that is ok.

**Comment by dereke** [comment]
find will never timeout as it doesn't actually do anything. find simple adds selectors to be executed when you call an action such as click/typeIn etc.
