### ISSUE TITLE
Text is considered as it appears in the HTML source, rather than as displayed

### ISSUE THREAD

**Issue by adiel** [featurist/browser-monkey#3]
```html
<p>
    That's
    not
    right
</p>
```
is expected to be "That's\n    not\n    right\n" when finding by / asserting on text

**Comment by refractalize** [comment]
so should normalise all white space in text to one space? `text.trim().replace(/\s+/g, ' ')`

**Comment by adiel** [comment]
It's as much about line breaks as whitespace. innerText gives you line breaks in the right place, then we normalise spaces incl at the beginning and end of a line. 

This is what Selenium does internally somewhere
