### ISSUE TITLE
Expect attributes on multiple elements

### ISSUE THREAD

**Issue by SachaZvetelman** [featurist/browser-monkey#47]
Currently you can do:
`page.titles().shouldHave({ text: ['Title 1', 'Title 2', 'Title 3'] });`

It would be useful to be able to do the same, but with attributes. Something like:
`page.titles().shouldHave({ attributes: { href: ['https://google.com/', 'https://google.co.uk/', 'https://google.com.ar/'] } });`

**Comment by dereke** [comment]
Ah this was implemented in v2.2.0 - https://github.com/featurist/browser-monkey/blob/master/CHANGELOG.md#220---2017-02-27

```
browser.find('img').shouldHave({
  attributes: [
    {src: '/monkey1.jpg', alt: 'first monkey'},
    {src: '/monkey2.jpg', alt: 'second monkey'},
  ]
})
```
