### ISSUE TITLE
should not be scoped to `body`

### ISSUE THREAD

**Issue by refractalize** [featurist/browser-monkey#49]
I've seen a couple of issues where people are doing `browser.find('body')` and not finding it. Seems a fairly natural first test. We should scope to `document`, not `document.body`.

**Comment by dereke** [comment]
I think I made this default to body to make it consistent across iframe/window, I think there was an issue scoping to `contentDocument`

**Comment by refractalize** [comment]
yeah i think we made the iframe scope the same as the normal window scope. But actually we should have done it the other way around.

**Comment by dereke** [comment]
haha yeah maybe, should try it and see I suppose

**Comment by dereke** [comment]
this has been implemented in #65
